name: readiness_ui
description: Readiness widgets
version: 0.0.1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  health_integration:
    path: ../health_integration

flutter:
  plugin:
    platforms: {}
