#!/bin/bash
# Quick start guide for Workout Planner local development

echo "=== Workout Planner Quick Start ==="
echo ""
echo "This script helps you get started with local development."
echo "For production deployment, see: https://github.com/srummel/infrastructure"
echo ""

echo "=== Local Development Setup ==="
echo ""
echo "1. Backend Setup:"
echo "   cd applications/backend/python_fastapi_server"
echo "   python -m venv .venv"
echo "   source .venv/bin/activate"
echo "   pip install -r requirements.txt"
echo "   uvicorn main:app --reload --port 8000"
echo ""
echo "2. Frontend Setup:"
echo "   cd applications/frontend/apps/mobile_app"
echo "   flutter pub get"
echo "   flutter run -d chrome --web-port 8081"
echo ""
echo "3. Optional: Local Database"
echo "   docker compose -f docker-compose.local.yml up -d"
echo ""
echo "=== Useful Scripts ==="
echo ""
echo "- scripts/run_local.sh           - Complete local environment"
echo "- scripts/flutter_checks.sh      - Run Flutter quality checks"
echo "- scripts/smoke_test.sh          - Quick health check"
echo "- scripts/setup_ai_chat.sh       - Initialize AI chat feature"
echo ""
echo "=== Documentation ==="
echo ""
echo "- Local: docs/README.md"
echo "- Architecture: docs/ARCHITECTURE.md"
echo "- Testing: docs/TESTING.md"
echo "- Deployment: https://github.com/srummel/infrastructure"
echo ""
